// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kamilsk/form-api/pkg/server/router (interfaces: Server)

// Package chi_test is a generated GoMock package.
package chi_test

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockServer is a mock of Server interface
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// GetV1 mocks base method
func (m *MockServer) GetV1(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.Call(m, "GetV1", arg0, arg1)
}

// GetV1 indicates an expected call of GetV1
func (mr *MockServerMockRecorder) GetV1(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetV1", reflect.TypeOf((*MockServer)(nil).GetV1), arg0, arg1)
}

// PostV1 mocks base method
func (m *MockServer) PostV1(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.Call(m, "PostV1", arg0, arg1)
}

// PostV1 indicates an expected call of PostV1
func (mr *MockServerMockRecorder) PostV1(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostV1", reflect.TypeOf((*MockServer)(nil).PostV1), arg0, arg1)
}
