TRUNCATE TABLE "link" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "schema" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "template" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "input" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "event" RESTART IDENTITY RESTRICT;
