// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadInputRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadInputRequest) Reset()         { *m = ReadInputRequest{} }
func (m *ReadInputRequest) String() string { return proto.CompactTextString(m) }
func (*ReadInputRequest) ProtoMessage()    {}
func (*ReadInputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{0}
}
func (m *ReadInputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadInputRequest.Unmarshal(m, b)
}
func (m *ReadInputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadInputRequest.Marshal(b, m, deterministic)
}
func (dst *ReadInputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadInputRequest.Merge(dst, src)
}
func (m *ReadInputRequest) XXX_Size() int {
	return xxx_messageInfo_ReadInputRequest.Size(m)
}
func (m *ReadInputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadInputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadInputRequest proto.InternalMessageInfo

type ReadInputResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadInputResponse) Reset()         { *m = ReadInputResponse{} }
func (m *ReadInputResponse) String() string { return proto.CompactTextString(m) }
func (*ReadInputResponse) ProtoMessage()    {}
func (*ReadInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{1}
}
func (m *ReadInputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadInputResponse.Unmarshal(m, b)
}
func (m *ReadInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadInputResponse.Marshal(b, m, deterministic)
}
func (dst *ReadInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadInputResponse.Merge(dst, src)
}
func (m *ReadInputResponse) XXX_Size() int {
	return xxx_messageInfo_ReadInputResponse.Size(m)
}
func (m *ReadInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadInputResponse proto.InternalMessageInfo

type ListenInputRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenInputRequest) Reset()         { *m = ListenInputRequest{} }
func (m *ListenInputRequest) String() string { return proto.CompactTextString(m) }
func (*ListenInputRequest) ProtoMessage()    {}
func (*ListenInputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{2}
}
func (m *ListenInputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenInputRequest.Unmarshal(m, b)
}
func (m *ListenInputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenInputRequest.Marshal(b, m, deterministic)
}
func (dst *ListenInputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenInputRequest.Merge(dst, src)
}
func (m *ListenInputRequest) XXX_Size() int {
	return xxx_messageInfo_ListenInputRequest.Size(m)
}
func (m *ListenInputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenInputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenInputRequest proto.InternalMessageInfo

type ListenInputResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenInputResponse) Reset()         { *m = ListenInputResponse{} }
func (m *ListenInputResponse) String() string { return proto.CompactTextString(m) }
func (*ListenInputResponse) ProtoMessage()    {}
func (*ListenInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{3}
}
func (m *ListenInputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenInputResponse.Unmarshal(m, b)
}
func (m *ListenInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenInputResponse.Marshal(b, m, deterministic)
}
func (dst *ListenInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenInputResponse.Merge(dst, src)
}
func (m *ListenInputResponse) XXX_Size() int {
	return xxx_messageInfo_ListenInputResponse.Size(m)
}
func (m *ListenInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenInputResponse proto.InternalMessageInfo

type ReadLogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogRequest) Reset()         { *m = ReadLogRequest{} }
func (m *ReadLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLogRequest) ProtoMessage()    {}
func (*ReadLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{4}
}
func (m *ReadLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogRequest.Unmarshal(m, b)
}
func (m *ReadLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogRequest.Marshal(b, m, deterministic)
}
func (dst *ReadLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogRequest.Merge(dst, src)
}
func (m *ReadLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLogRequest.Size(m)
}
func (m *ReadLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogRequest proto.InternalMessageInfo

type ReadLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogResponse) Reset()         { *m = ReadLogResponse{} }
func (m *ReadLogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLogResponse) ProtoMessage()    {}
func (*ReadLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{5}
}
func (m *ReadLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogResponse.Unmarshal(m, b)
}
func (m *ReadLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogResponse.Marshal(b, m, deterministic)
}
func (dst *ReadLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogResponse.Merge(dst, src)
}
func (m *ReadLogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLogResponse.Size(m)
}
func (m *ReadLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogResponse proto.InternalMessageInfo

type ListenLogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenLogRequest) Reset()         { *m = ListenLogRequest{} }
func (m *ListenLogRequest) String() string { return proto.CompactTextString(m) }
func (*ListenLogRequest) ProtoMessage()    {}
func (*ListenLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{6}
}
func (m *ListenLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenLogRequest.Unmarshal(m, b)
}
func (m *ListenLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenLogRequest.Marshal(b, m, deterministic)
}
func (dst *ListenLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenLogRequest.Merge(dst, src)
}
func (m *ListenLogRequest) XXX_Size() int {
	return xxx_messageInfo_ListenLogRequest.Size(m)
}
func (m *ListenLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenLogRequest proto.InternalMessageInfo

type ListenLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenLogResponse) Reset()         { *m = ListenLogResponse{} }
func (m *ListenLogResponse) String() string { return proto.CompactTextString(m) }
func (*ListenLogResponse) ProtoMessage()    {}
func (*ListenLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_875ab0283ce70bf1, []int{7}
}
func (m *ListenLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenLogResponse.Unmarshal(m, b)
}
func (m *ListenLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenLogResponse.Marshal(b, m, deterministic)
}
func (dst *ListenLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenLogResponse.Merge(dst, src)
}
func (m *ListenLogResponse) XXX_Size() int {
	return xxx_messageInfo_ListenLogResponse.Size(m)
}
func (m *ListenLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenLogResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReadInputRequest)(nil), "grpc.ReadInputRequest")
	proto.RegisterType((*ReadInputResponse)(nil), "grpc.ReadInputResponse")
	proto.RegisterType((*ListenInputRequest)(nil), "grpc.ListenInputRequest")
	proto.RegisterType((*ListenInputResponse)(nil), "grpc.ListenInputResponse")
	proto.RegisterType((*ReadLogRequest)(nil), "grpc.ReadLogRequest")
	proto.RegisterType((*ReadLogResponse)(nil), "grpc.ReadLogResponse")
	proto.RegisterType((*ListenLogRequest)(nil), "grpc.ListenLogRequest")
	proto.RegisterType((*ListenLogResponse)(nil), "grpc.ListenLogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InputClient is the client API for Input service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InputClient interface {
	Read(ctx context.Context, in *ReadInputRequest, opts ...grpc.CallOption) (*ReadInputResponse, error)
	Listen(ctx context.Context, in *ListenInputRequest, opts ...grpc.CallOption) (Input_ListenClient, error)
}

type inputClient struct {
	cc *grpc.ClientConn
}

func NewInputClient(cc *grpc.ClientConn) InputClient {
	return &inputClient{cc}
}

func (c *inputClient) Read(ctx context.Context, in *ReadInputRequest, opts ...grpc.CallOption) (*ReadInputResponse, error) {
	out := new(ReadInputResponse)
	err := c.cc.Invoke(ctx, "/grpc.Input/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inputClient) Listen(ctx context.Context, in *ListenInputRequest, opts ...grpc.CallOption) (Input_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Input_serviceDesc.Streams[0], "/grpc.Input/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &inputListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Input_ListenClient interface {
	Recv() (*ListenInputResponse, error)
	grpc.ClientStream
}

type inputListenClient struct {
	grpc.ClientStream
}

func (x *inputListenClient) Recv() (*ListenInputResponse, error) {
	m := new(ListenInputResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InputServer is the server API for Input service.
type InputServer interface {
	Read(context.Context, *ReadInputRequest) (*ReadInputResponse, error)
	Listen(*ListenInputRequest, Input_ListenServer) error
}

func RegisterInputServer(s *grpc.Server, srv InputServer) {
	s.RegisterService(&_Input_serviceDesc, srv)
}

func _Input_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Input/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputServer).Read(ctx, req.(*ReadInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Input_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenInputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InputServer).Listen(m, &inputListenServer{stream})
}

type Input_ListenServer interface {
	Send(*ListenInputResponse) error
	grpc.ServerStream
}

type inputListenServer struct {
	grpc.ServerStream
}

func (x *inputListenServer) Send(m *ListenInputResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Input_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Input",
	HandlerType: (*InputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Input_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Input_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	Read(ctx context.Context, in *ReadLogRequest, opts ...grpc.CallOption) (*ReadLogResponse, error)
	Listen(ctx context.Context, in *ListenLogRequest, opts ...grpc.CallOption) (Log_ListenClient, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) Read(ctx context.Context, in *ReadLogRequest, opts ...grpc.CallOption) (*ReadLogResponse, error) {
	out := new(ReadLogResponse)
	err := c.cc.Invoke(ctx, "/grpc.Log/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Listen(ctx context.Context, in *ListenLogRequest, opts ...grpc.CallOption) (Log_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Log_serviceDesc.Streams[0], "/grpc.Log/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &logListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Log_ListenClient interface {
	Recv() (*ListenLogResponse, error)
	grpc.ClientStream
}

type logListenClient struct {
	grpc.ClientStream
}

func (x *logListenClient) Recv() (*ListenLogResponse, error) {
	m := new(ListenLogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	Read(context.Context, *ReadLogRequest) (*ReadLogResponse, error)
	Listen(*ListenLogRequest, Log_ListenServer) error
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Log/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Read(ctx, req.(*ReadLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServer).Listen(m, &logListenServer{stream})
}

type Log_ListenServer interface {
	Send(*ListenLogResponse) error
	grpc.ServerStream
}

type logListenServer struct {
	grpc.ServerStream
}

func (x *logListenServer) Send(m *ListenLogResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Log_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Log_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_875ab0283ce70bf1) }

var fileDescriptor_event_875ab0283ce70bf1 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x12, 0xe2,
	0x12, 0x08, 0x4a, 0x4d, 0x4c, 0xf1, 0xcc, 0x2b, 0x28, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x51, 0x12, 0xe6, 0x12, 0x44, 0x12, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x12, 0xe1,
	0x12, 0xf2, 0xc9, 0x2c, 0x2e, 0x49, 0xcd, 0x43, 0x51, 0x2a, 0xca, 0x25, 0x8c, 0x22, 0x0a, 0x55,
	0x2c, 0xc0, 0xc5, 0x07, 0x32, 0xc1, 0x27, 0x3f, 0x1d, 0xa6, 0x50, 0x90, 0x8b, 0x1f, 0x2e, 0x02,
	0x55, 0x24, 0xc4, 0x25, 0x00, 0xd1, 0x8b, 0xa4, 0x4c, 0x98, 0x4b, 0x10, 0x49, 0x0c, 0xa2, 0xd0,
	0xa8, 0x95, 0x91, 0x8b, 0x15, 0x6c, 0xbe, 0x90, 0x25, 0x17, 0x0b, 0xc8, 0x14, 0x21, 0x31, 0x3d,
	0x90, 0xe3, 0xf5, 0xd0, 0x5d, 0x2e, 0x25, 0x8e, 0x21, 0x0e, 0xb5, 0x8b, 0x41, 0xc8, 0x91, 0x8b,
	0x0d, 0x62, 0xb2, 0x90, 0x04, 0x44, 0x11, 0xa6, 0x6f, 0xa4, 0x24, 0xb1, 0xc8, 0xc0, 0x0c, 0x30,
	0x60, 0x34, 0xaa, 0xe6, 0x62, 0xf6, 0xc9, 0x4f, 0x17, 0x32, 0x85, 0x3a, 0x42, 0x04, 0x61, 0x19,
	0xc2, 0x07, 0x52, 0xa2, 0x68, 0xa2, 0x70, 0x07, 0xd8, 0xc2, 0x1d, 0x20, 0x86, 0x6c, 0x0d, 0x92,
	0x56, 0x71, 0x0c, 0x71, 0x84, 0xe5, 0x49, 0x6c, 0xe0, 0x58, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe8, 0x59, 0x18, 0xf1, 0xc4, 0x01, 0x00, 0x00,
}
