// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaRequest) Reset()         { *m = CreateSchemaRequest{} }
func (m *CreateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaRequest) ProtoMessage()    {}
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{0}
}
func (m *CreateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaRequest.Unmarshal(m, b)
}
func (m *CreateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaRequest.Merge(dst, src)
}
func (m *CreateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaRequest.Size(m)
}
func (m *CreateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaRequest proto.InternalMessageInfo

type CreateSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaResponse) Reset()         { *m = CreateSchemaResponse{} }
func (m *CreateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaResponse) ProtoMessage()    {}
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{1}
}
func (m *CreateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaResponse.Unmarshal(m, b)
}
func (m *CreateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaResponse.Merge(dst, src)
}
func (m *CreateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaResponse.Size(m)
}
func (m *CreateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaResponse proto.InternalMessageInfo

type ReadSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSchemaRequest) Reset()         { *m = ReadSchemaRequest{} }
func (m *ReadSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaRequest) ProtoMessage()    {}
func (*ReadSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{2}
}
func (m *ReadSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaRequest.Unmarshal(m, b)
}
func (m *ReadSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaRequest.Merge(dst, src)
}
func (m *ReadSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaRequest.Size(m)
}
func (m *ReadSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaRequest proto.InternalMessageInfo

type ReadSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSchemaResponse) Reset()         { *m = ReadSchemaResponse{} }
func (m *ReadSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaResponse) ProtoMessage()    {}
func (*ReadSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{3}
}
func (m *ReadSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaResponse.Unmarshal(m, b)
}
func (m *ReadSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaResponse.Merge(dst, src)
}
func (m *ReadSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaResponse.Size(m)
}
func (m *ReadSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaResponse proto.InternalMessageInfo

type UpdateSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaRequest) Reset()         { *m = UpdateSchemaRequest{} }
func (m *UpdateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaRequest) ProtoMessage()    {}
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{4}
}
func (m *UpdateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaRequest.Unmarshal(m, b)
}
func (m *UpdateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaRequest.Merge(dst, src)
}
func (m *UpdateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaRequest.Size(m)
}
func (m *UpdateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaRequest proto.InternalMessageInfo

type UpdateSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaResponse) Reset()         { *m = UpdateSchemaResponse{} }
func (m *UpdateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaResponse) ProtoMessage()    {}
func (*UpdateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{5}
}
func (m *UpdateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaResponse.Unmarshal(m, b)
}
func (m *UpdateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaResponse.Merge(dst, src)
}
func (m *UpdateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaResponse.Size(m)
}
func (m *UpdateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaResponse proto.InternalMessageInfo

type DeleteSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaRequest) Reset()         { *m = DeleteSchemaRequest{} }
func (m *DeleteSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaRequest) ProtoMessage()    {}
func (*DeleteSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{6}
}
func (m *DeleteSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaRequest.Unmarshal(m, b)
}
func (m *DeleteSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaRequest.Merge(dst, src)
}
func (m *DeleteSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaRequest.Size(m)
}
func (m *DeleteSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaRequest proto.InternalMessageInfo

type DeleteSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaResponse) Reset()         { *m = DeleteSchemaResponse{} }
func (m *DeleteSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaResponse) ProtoMessage()    {}
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{7}
}
func (m *DeleteSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaResponse.Unmarshal(m, b)
}
func (m *DeleteSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaResponse.Merge(dst, src)
}
func (m *DeleteSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaResponse.Size(m)
}
func (m *DeleteSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaResponse proto.InternalMessageInfo

type CreateTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTemplateRequest) Reset()         { *m = CreateTemplateRequest{} }
func (m *CreateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateRequest) ProtoMessage()    {}
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{8}
}
func (m *CreateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateRequest.Unmarshal(m, b)
}
func (m *CreateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateRequest.Merge(dst, src)
}
func (m *CreateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateRequest.Size(m)
}
func (m *CreateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateRequest proto.InternalMessageInfo

type CreateTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTemplateResponse) Reset()         { *m = CreateTemplateResponse{} }
func (m *CreateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateResponse) ProtoMessage()    {}
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{9}
}
func (m *CreateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateResponse.Unmarshal(m, b)
}
func (m *CreateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateResponse.Merge(dst, src)
}
func (m *CreateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateResponse.Size(m)
}
func (m *CreateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateResponse proto.InternalMessageInfo

type ReadTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTemplateRequest) Reset()         { *m = ReadTemplateRequest{} }
func (m *ReadTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateRequest) ProtoMessage()    {}
func (*ReadTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{10}
}
func (m *ReadTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateRequest.Unmarshal(m, b)
}
func (m *ReadTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateRequest.Merge(dst, src)
}
func (m *ReadTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateRequest.Size(m)
}
func (m *ReadTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateRequest proto.InternalMessageInfo

type ReadTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTemplateResponse) Reset()         { *m = ReadTemplateResponse{} }
func (m *ReadTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateResponse) ProtoMessage()    {}
func (*ReadTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{11}
}
func (m *ReadTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateResponse.Unmarshal(m, b)
}
func (m *ReadTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateResponse.Merge(dst, src)
}
func (m *ReadTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateResponse.Size(m)
}
func (m *ReadTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateResponse proto.InternalMessageInfo

type UpdateTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTemplateRequest) Reset()         { *m = UpdateTemplateRequest{} }
func (m *UpdateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateRequest) ProtoMessage()    {}
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{12}
}
func (m *UpdateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateRequest.Unmarshal(m, b)
}
func (m *UpdateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateRequest.Merge(dst, src)
}
func (m *UpdateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateRequest.Size(m)
}
func (m *UpdateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateRequest proto.InternalMessageInfo

type UpdateTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{13}
}
func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(dst, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

type DeleteTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTemplateRequest) Reset()         { *m = DeleteTemplateRequest{} }
func (m *DeleteTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateRequest) ProtoMessage()    {}
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{14}
}
func (m *DeleteTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateRequest.Unmarshal(m, b)
}
func (m *DeleteTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateRequest.Merge(dst, src)
}
func (m *DeleteTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateRequest.Size(m)
}
func (m *DeleteTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateRequest proto.InternalMessageInfo

type DeleteTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTemplateResponse) Reset()         { *m = DeleteTemplateResponse{} }
func (m *DeleteTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateResponse) ProtoMessage()    {}
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_aa281a22ef7543e5, []int{15}
}
func (m *DeleteTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateResponse.Unmarshal(m, b)
}
func (m *DeleteTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateResponse.Merge(dst, src)
}
func (m *DeleteTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateResponse.Size(m)
}
func (m *DeleteTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateSchemaRequest)(nil), "grpc.CreateSchemaRequest")
	proto.RegisterType((*CreateSchemaResponse)(nil), "grpc.CreateSchemaResponse")
	proto.RegisterType((*ReadSchemaRequest)(nil), "grpc.ReadSchemaRequest")
	proto.RegisterType((*ReadSchemaResponse)(nil), "grpc.ReadSchemaResponse")
	proto.RegisterType((*UpdateSchemaRequest)(nil), "grpc.UpdateSchemaRequest")
	proto.RegisterType((*UpdateSchemaResponse)(nil), "grpc.UpdateSchemaResponse")
	proto.RegisterType((*DeleteSchemaRequest)(nil), "grpc.DeleteSchemaRequest")
	proto.RegisterType((*DeleteSchemaResponse)(nil), "grpc.DeleteSchemaResponse")
	proto.RegisterType((*CreateTemplateRequest)(nil), "grpc.CreateTemplateRequest")
	proto.RegisterType((*CreateTemplateResponse)(nil), "grpc.CreateTemplateResponse")
	proto.RegisterType((*ReadTemplateRequest)(nil), "grpc.ReadTemplateRequest")
	proto.RegisterType((*ReadTemplateResponse)(nil), "grpc.ReadTemplateResponse")
	proto.RegisterType((*UpdateTemplateRequest)(nil), "grpc.UpdateTemplateRequest")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "grpc.UpdateTemplateResponse")
	proto.RegisterType((*DeleteTemplateRequest)(nil), "grpc.DeleteTemplateRequest")
	proto.RegisterType((*DeleteTemplateResponse)(nil), "grpc.DeleteTemplateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchemaClient is the client API for Schema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchemaClient interface {
	Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error)
	Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error)
	Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error)
	Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
}

type schemaClient struct {
	cc *grpc.ClientConn
}

func NewSchemaClient(cc *grpc.ClientConn) SchemaClient {
	return &schemaClient{cc}
}

func (c *schemaClient) Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error) {
	out := new(CreateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error) {
	out := new(ReadSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error) {
	out := new(UpdateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServer is the server API for Schema service.
type SchemaServer interface {
	Create(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error)
	Read(context.Context, *ReadSchemaRequest) (*ReadSchemaResponse, error)
	Update(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error)
	Delete(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
}

func RegisterSchemaServer(s *grpc.Server, srv SchemaServer) {
	s.RegisterService(&_Schema_serviceDesc, srv)
}

func _Schema_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Create(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Read(ctx, req.(*ReadSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Update(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Delete(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Schema_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Schema",
	HandlerType: (*SchemaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Schema_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Schema_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Schema_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Schema_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateClient interface {
	Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error)
	Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
}

type templateClient struct {
	cc *grpc.ClientConn
}

func NewTemplateClient(cc *grpc.ClientConn) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error) {
	out := new(ReadTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
type TemplateServer interface {
	Create(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	Read(context.Context, *ReadTemplateRequest) (*ReadTemplateResponse, error)
	Update(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error)
	Delete(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
}

func RegisterTemplateServer(s *grpc.Server, srv TemplateServer) {
	s.RegisterService(&_Template_serviceDesc, srv)
}

func _Template_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Create(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Read(ctx, req.(*ReadTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Update(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Delete(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Template_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Template_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Template_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Template_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Template_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_aa281a22ef7543e5) }

var fileDescriptor_storage_aa281a22ef7543e5 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0xad, 0xaa, 0x2a, 0x42, 0x23, 0xb1, 0xc0, 0xf9, 0xb4, 0x75, 0x58, 0xe5, 0x00, 0x59, 0x94,
	0x25, 0x0b, 0x54, 0x41, 0x2f, 0x50, 0xe0, 0x00, 0xa6, 0x1d, 0x95, 0x45, 0x4b, 0x4c, 0x62, 0xae,
	0xc1, 0x19, 0x38, 0x2a, 0x4a, 0xfc, 0x8b, 0xdd, 0xc9, 0x76, 0x3e, 0x6f, 0xde, 0xc7, 0x86, 0xdb,
	0x4e, 0x35, 0xad, 0x38, 0x61, 0x2d, 0xdb, 0x46, 0x35, 0x6c, 0x71, 0x6a, 0xe5, 0xa1, 0xca, 0x21,
	0x7d, 0x6e, 0x51, 0x28, 0x7c, 0x3d, 0x7c, 0xe2, 0x45, 0xec, 0xf1, 0xfb, 0x07, 0x3b, 0x55, 0x15,
	0x90, 0x85, 0xe5, 0x4e, 0x36, 0x5f, 0x1d, 0x56, 0x29, 0xdc, 0xed, 0x51, 0x1c, 0xc3, 0xe1, 0x0c,
	0xd8, 0xb8, 0x68, 0x46, 0x73, 0x48, 0xdf, 0xe5, 0x91, 0x42, 0x0e, 0xcb, 0x7e, 0xfc, 0x05, 0xcf,
	0x48, 0x8c, 0x87, 0x65, 0x33, 0xbe, 0x84, 0x5c, 0x13, 0x7c, 0xc3, 0x8b, 0x3c, 0x0b, 0x85, 0x76,
	0x61, 0x05, 0x45, 0xdc, 0xf0, 0x17, 0x7a, 0x9a, 0xf1, 0x42, 0x01, 0x59, 0x58, 0xf6, 0x17, 0x34,
	0x51, 0xe2, 0x42, 0xdc, 0xf0, 0x2b, 0x9a, 0x2c, 0xb1, 0x12, 0x37, 0xf4, 0xca, 0xe6, 0x77, 0x0e,
	0x89, 0x96, 0xc6, 0xb6, 0x90, 0x68, 0xe6, 0x6c, 0x5d, 0xf7, 0xd9, 0xd4, 0x44, 0x30, 0x9c, 0x53,
	0x2d, 0x73, 0x7e, 0xc6, 0x1e, 0x61, 0xd1, 0x6b, 0x61, 0x4b, 0x3d, 0x75, 0x15, 0x15, 0x5f, 0x5d,
	0x37, 0xdc, 0xf2, 0x16, 0x12, 0xad, 0xcb, 0xde, 0x27, 0xe2, 0xb3, 0xf7, 0xc9, 0x08, 0x07, 0x08,
	0xad, 0xd3, 0x42, 0x10, 0x91, 0x5a, 0x08, 0x32, 0xd6, 0xd9, 0xe6, 0x6f, 0x0e, 0x37, 0xd6, 0x25,
	0xb6, 0x73, 0x96, 0x94, 0x63, 0xdd, 0x91, 0xbd, 0xfc, 0x9e, 0x6e, 0x3a, 0x5a, 0x4f, 0xc6, 0x96,
	0xb5, 0x57, 0x1f, 0x43, 0x70, 0xaa, 0xe5, 0x00, 0x76, 0xce, 0x9a, 0x72, 0xac, 0x7f, 0x82, 0xc7,
	0xc4, 0xeb, 0x18, 0x60, 0x8c, 0x3d, 0xe5, 0xd8, 0x83, 0x09, 0x18, 0xfa, 0xc5, 0x54, 0xb3, 0x8f,
	0x64, 0xf8, 0xc0, 0x0f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0x50, 0x5f, 0x57, 0xd1, 0x03,
	0x00, 0x00,
}
