// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Error from common.proto

// Ignoring public import of TimestampRange from common.proto

type CreateSchemaRequest struct {
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string   `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaRequest) Reset()         { *m = CreateSchemaRequest{} }
func (m *CreateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaRequest) ProtoMessage()    {}
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{0}
}
func (m *CreateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaRequest.Unmarshal(m, b)
}
func (m *CreateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaRequest.Merge(dst, src)
}
func (m *CreateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaRequest.Size(m)
}
func (m *CreateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaRequest proto.InternalMessageInfo

func (m *CreateSchemaRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CreateSchemaRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateSchemaRequest) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type CreateSchemaResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateSchemaResponse) Reset()         { *m = CreateSchemaResponse{} }
func (m *CreateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaResponse) ProtoMessage()    {}
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{1}
}
func (m *CreateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaResponse.Unmarshal(m, b)
}
func (m *CreateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaResponse.Merge(dst, src)
}
func (m *CreateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaResponse.Size(m)
}
func (m *CreateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaResponse proto.InternalMessageInfo

func (m *CreateSchemaResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateSchemaResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateSchemaResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type ReadSchemaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSchemaRequest) Reset()         { *m = ReadSchemaRequest{} }
func (m *ReadSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaRequest) ProtoMessage()    {}
func (*ReadSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{2}
}
func (m *ReadSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaRequest.Unmarshal(m, b)
}
func (m *ReadSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaRequest.Merge(dst, src)
}
func (m *ReadSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaRequest.Size(m)
}
func (m *ReadSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaRequest proto.InternalMessageInfo

func (m *ReadSchemaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadSchemaResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Language             string               `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string               `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadSchemaResponse) Reset()         { *m = ReadSchemaResponse{} }
func (m *ReadSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaResponse) ProtoMessage()    {}
func (*ReadSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{3}
}
func (m *ReadSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaResponse.Unmarshal(m, b)
}
func (m *ReadSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaResponse.Merge(dst, src)
}
func (m *ReadSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaResponse.Size(m)
}
func (m *ReadSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaResponse proto.InternalMessageInfo

func (m *ReadSchemaResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadSchemaResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ReadSchemaResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReadSchemaResponse) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *ReadSchemaResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadSchemaResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadSchemaResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *ReadSchemaResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type UpdateSchemaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string   `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaRequest) Reset()         { *m = UpdateSchemaRequest{} }
func (m *UpdateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaRequest) ProtoMessage()    {}
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{4}
}
func (m *UpdateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaRequest.Unmarshal(m, b)
}
func (m *UpdateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaRequest.Merge(dst, src)
}
func (m *UpdateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaRequest.Size(m)
}
func (m *UpdateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaRequest proto.InternalMessageInfo

func (m *UpdateSchemaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateSchemaRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *UpdateSchemaRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateSchemaRequest) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type UpdateSchemaResponse struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateSchemaResponse) Reset()         { *m = UpdateSchemaResponse{} }
func (m *UpdateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaResponse) ProtoMessage()    {}
func (*UpdateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{5}
}
func (m *UpdateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaResponse.Unmarshal(m, b)
}
func (m *UpdateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaResponse.Merge(dst, src)
}
func (m *UpdateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaResponse.Size(m)
}
func (m *UpdateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaResponse proto.InternalMessageInfo

func (m *UpdateSchemaResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UpdateSchemaResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type DeleteSchemaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaRequest) Reset()         { *m = DeleteSchemaRequest{} }
func (m *DeleteSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaRequest) ProtoMessage()    {}
func (*DeleteSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{6}
}
func (m *DeleteSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaRequest.Unmarshal(m, b)
}
func (m *DeleteSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaRequest.Merge(dst, src)
}
func (m *DeleteSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaRequest.Size(m)
}
func (m *DeleteSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaRequest proto.InternalMessageInfo

func (m *DeleteSchemaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteSchemaResponse struct {
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteSchemaResponse) Reset()         { *m = DeleteSchemaResponse{} }
func (m *DeleteSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaResponse) ProtoMessage()    {}
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{7}
}
func (m *DeleteSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaResponse.Unmarshal(m, b)
}
func (m *DeleteSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaResponse.Merge(dst, src)
}
func (m *DeleteSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaResponse.Size(m)
}
func (m *DeleteSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaResponse proto.InternalMessageInfo

func (m *DeleteSchemaResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *DeleteSchemaResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type CreateTemplateRequest struct {
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string   `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTemplateRequest) Reset()         { *m = CreateTemplateRequest{} }
func (m *CreateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateRequest) ProtoMessage()    {}
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{8}
}
func (m *CreateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateRequest.Unmarshal(m, b)
}
func (m *CreateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateRequest.Merge(dst, src)
}
func (m *CreateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateRequest.Size(m)
}
func (m *CreateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateRequest proto.InternalMessageInfo

func (m *CreateTemplateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateTemplateRequest) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type CreateTemplateResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTemplateResponse) Reset()         { *m = CreateTemplateResponse{} }
func (m *CreateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateResponse) ProtoMessage()    {}
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{9}
}
func (m *CreateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateResponse.Unmarshal(m, b)
}
func (m *CreateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateResponse.Merge(dst, src)
}
func (m *CreateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateResponse.Size(m)
}
func (m *CreateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateResponse proto.InternalMessageInfo

func (m *CreateTemplateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateTemplateResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateTemplateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type ReadTemplateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTemplateRequest) Reset()         { *m = ReadTemplateRequest{} }
func (m *ReadTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateRequest) ProtoMessage()    {}
func (*ReadTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{10}
}
func (m *ReadTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateRequest.Unmarshal(m, b)
}
func (m *ReadTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateRequest.Merge(dst, src)
}
func (m *ReadTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateRequest.Size(m)
}
func (m *ReadTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateRequest proto.InternalMessageInfo

func (m *ReadTemplateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadTemplateResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string               `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadTemplateResponse) Reset()         { *m = ReadTemplateResponse{} }
func (m *ReadTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateResponse) ProtoMessage()    {}
func (*ReadTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{11}
}
func (m *ReadTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateResponse.Unmarshal(m, b)
}
func (m *ReadTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateResponse.Merge(dst, src)
}
func (m *ReadTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateResponse.Size(m)
}
func (m *ReadTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateResponse proto.InternalMessageInfo

func (m *ReadTemplateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadTemplateResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReadTemplateResponse) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *ReadTemplateResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadTemplateResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadTemplateResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *ReadTemplateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type UpdateTemplateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Definition           string   `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTemplateRequest) Reset()         { *m = UpdateTemplateRequest{} }
func (m *UpdateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateRequest) ProtoMessage()    {}
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{12}
}
func (m *UpdateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateRequest.Unmarshal(m, b)
}
func (m *UpdateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateRequest.Merge(dst, src)
}
func (m *UpdateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateRequest.Size(m)
}
func (m *UpdateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateRequest proto.InternalMessageInfo

func (m *UpdateTemplateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTemplateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateTemplateRequest) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type UpdateTemplateResponse struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{13}
}
func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(dst, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

func (m *UpdateTemplateResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UpdateTemplateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type DeleteTemplateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTemplateRequest) Reset()         { *m = DeleteTemplateRequest{} }
func (m *DeleteTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateRequest) ProtoMessage()    {}
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{14}
}
func (m *DeleteTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateRequest.Unmarshal(m, b)
}
func (m *DeleteTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateRequest.Merge(dst, src)
}
func (m *DeleteTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateRequest.Size(m)
}
func (m *DeleteTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateRequest proto.InternalMessageInfo

func (m *DeleteTemplateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTemplateResponse struct {
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Err                  *Error               `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteTemplateResponse) Reset()         { *m = DeleteTemplateResponse{} }
func (m *DeleteTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateResponse) ProtoMessage()    {}
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{15}
}
func (m *DeleteTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateResponse.Unmarshal(m, b)
}
func (m *DeleteTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateResponse.Merge(dst, src)
}
func (m *DeleteTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateResponse.Size(m)
}
func (m *DeleteTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateResponse proto.InternalMessageInfo

func (m *DeleteTemplateResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *DeleteTemplateResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type InputEntry struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaId             string               `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Data                 []byte               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InputEntry) Reset()         { *m = InputEntry{} }
func (m *InputEntry) String() string { return proto.CompactTextString(m) }
func (*InputEntry) ProtoMessage()    {}
func (*InputEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{16}
}
func (m *InputEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputEntry.Unmarshal(m, b)
}
func (m *InputEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputEntry.Marshal(b, m, deterministic)
}
func (dst *InputEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputEntry.Merge(dst, src)
}
func (m *InputEntry) XXX_Size() int {
	return xxx_messageInfo_InputEntry.Size(m)
}
func (m *InputEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_InputEntry.DiscardUnknown(m)
}

var xxx_messageInfo_InputEntry proto.InternalMessageInfo

func (m *InputEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InputEntry) GetSchemaId() string {
	if m != nil {
		return m.SchemaId
	}
	return ""
}

func (m *InputEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InputEntry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type InputFilter struct {
	SchemaId             string          `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	CreatedAt            *TimestampRange `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InputFilter) Reset()         { *m = InputFilter{} }
func (m *InputFilter) String() string { return proto.CompactTextString(m) }
func (*InputFilter) ProtoMessage()    {}
func (*InputFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{17}
}
func (m *InputFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputFilter.Unmarshal(m, b)
}
func (m *InputFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputFilter.Marshal(b, m, deterministic)
}
func (dst *InputFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputFilter.Merge(dst, src)
}
func (m *InputFilter) XXX_Size() int {
	return xxx_messageInfo_InputFilter.Size(m)
}
func (m *InputFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_InputFilter.DiscardUnknown(m)
}

var xxx_messageInfo_InputFilter proto.InternalMessageInfo

func (m *InputFilter) GetSchemaId() string {
	if m != nil {
		return m.SchemaId
	}
	return ""
}

func (m *InputFilter) GetCreatedAt() *TimestampRange {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadInputRequest struct {
	// Types that are valid to be assigned to Filter:
	//	*ReadInputRequest_Id
	//	*ReadInputRequest_Condition
	Filter               isReadInputRequest_Filter `protobuf_oneof:"filter"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ReadInputRequest) Reset()         { *m = ReadInputRequest{} }
func (m *ReadInputRequest) String() string { return proto.CompactTextString(m) }
func (*ReadInputRequest) ProtoMessage()    {}
func (*ReadInputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{18}
}
func (m *ReadInputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadInputRequest.Unmarshal(m, b)
}
func (m *ReadInputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadInputRequest.Marshal(b, m, deterministic)
}
func (dst *ReadInputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadInputRequest.Merge(dst, src)
}
func (m *ReadInputRequest) XXX_Size() int {
	return xxx_messageInfo_ReadInputRequest.Size(m)
}
func (m *ReadInputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadInputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadInputRequest proto.InternalMessageInfo

type isReadInputRequest_Filter interface {
	isReadInputRequest_Filter()
}

type ReadInputRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}
type ReadInputRequest_Condition struct {
	Condition *InputFilter `protobuf:"bytes,2,opt,name=condition,proto3,oneof"`
}

func (*ReadInputRequest_Id) isReadInputRequest_Filter()        {}
func (*ReadInputRequest_Condition) isReadInputRequest_Filter() {}

func (m *ReadInputRequest) GetFilter() isReadInputRequest_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ReadInputRequest) GetId() string {
	if x, ok := m.GetFilter().(*ReadInputRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (m *ReadInputRequest) GetCondition() *InputFilter {
	if x, ok := m.GetFilter().(*ReadInputRequest_Condition); ok {
		return x.Condition
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReadInputRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReadInputRequest_OneofMarshaler, _ReadInputRequest_OneofUnmarshaler, _ReadInputRequest_OneofSizer, []interface{}{
		(*ReadInputRequest_Id)(nil),
		(*ReadInputRequest_Condition)(nil),
	}
}

func _ReadInputRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReadInputRequest)
	// filter
	switch x := m.Filter.(type) {
	case *ReadInputRequest_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case *ReadInputRequest_Condition:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Condition); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReadInputRequest.Filter has unexpected type %T", x)
	}
	return nil
}

func _ReadInputRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReadInputRequest)
	switch tag {
	case 1: // filter.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Filter = &ReadInputRequest_Id{x}
		return true, err
	case 2: // filter.condition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InputFilter)
		err := b.DecodeMessage(msg)
		m.Filter = &ReadInputRequest_Condition{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReadInputRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReadInputRequest)
	// filter
	switch x := m.Filter.(type) {
	case *ReadInputRequest_Id:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case *ReadInputRequest_Condition:
		s := proto.Size(x.Condition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReadInputResponse struct {
	Entries              []*InputEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Err                  *Error        `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadInputResponse) Reset()         { *m = ReadInputResponse{} }
func (m *ReadInputResponse) String() string { return proto.CompactTextString(m) }
func (*ReadInputResponse) ProtoMessage()    {}
func (*ReadInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_4fed8f99a8a63f42, []int{19}
}
func (m *ReadInputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadInputResponse.Unmarshal(m, b)
}
func (m *ReadInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadInputResponse.Marshal(b, m, deterministic)
}
func (dst *ReadInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadInputResponse.Merge(dst, src)
}
func (m *ReadInputResponse) XXX_Size() int {
	return xxx_messageInfo_ReadInputResponse.Size(m)
}
func (m *ReadInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadInputResponse proto.InternalMessageInfo

func (m *ReadInputResponse) GetEntries() []*InputEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *ReadInputResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSchemaRequest)(nil), "grpc.CreateSchemaRequest")
	proto.RegisterType((*CreateSchemaResponse)(nil), "grpc.CreateSchemaResponse")
	proto.RegisterType((*ReadSchemaRequest)(nil), "grpc.ReadSchemaRequest")
	proto.RegisterType((*ReadSchemaResponse)(nil), "grpc.ReadSchemaResponse")
	proto.RegisterType((*UpdateSchemaRequest)(nil), "grpc.UpdateSchemaRequest")
	proto.RegisterType((*UpdateSchemaResponse)(nil), "grpc.UpdateSchemaResponse")
	proto.RegisterType((*DeleteSchemaRequest)(nil), "grpc.DeleteSchemaRequest")
	proto.RegisterType((*DeleteSchemaResponse)(nil), "grpc.DeleteSchemaResponse")
	proto.RegisterType((*CreateTemplateRequest)(nil), "grpc.CreateTemplateRequest")
	proto.RegisterType((*CreateTemplateResponse)(nil), "grpc.CreateTemplateResponse")
	proto.RegisterType((*ReadTemplateRequest)(nil), "grpc.ReadTemplateRequest")
	proto.RegisterType((*ReadTemplateResponse)(nil), "grpc.ReadTemplateResponse")
	proto.RegisterType((*UpdateTemplateRequest)(nil), "grpc.UpdateTemplateRequest")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "grpc.UpdateTemplateResponse")
	proto.RegisterType((*DeleteTemplateRequest)(nil), "grpc.DeleteTemplateRequest")
	proto.RegisterType((*DeleteTemplateResponse)(nil), "grpc.DeleteTemplateResponse")
	proto.RegisterType((*InputEntry)(nil), "grpc.InputEntry")
	proto.RegisterType((*InputFilter)(nil), "grpc.InputFilter")
	proto.RegisterType((*ReadInputRequest)(nil), "grpc.ReadInputRequest")
	proto.RegisterType((*ReadInputResponse)(nil), "grpc.ReadInputResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchemaClient is the client API for Schema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchemaClient interface {
	Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error)
	Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error)
	Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error)
	Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
}

type schemaClient struct {
	cc *grpc.ClientConn
}

func NewSchemaClient(cc *grpc.ClientConn) SchemaClient {
	return &schemaClient{cc}
}

func (c *schemaClient) Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error) {
	out := new(CreateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error) {
	out := new(ReadSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error) {
	out := new(UpdateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServer is the server API for Schema service.
type SchemaServer interface {
	Create(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error)
	Read(context.Context, *ReadSchemaRequest) (*ReadSchemaResponse, error)
	Update(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error)
	Delete(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
}

func RegisterSchemaServer(s *grpc.Server, srv SchemaServer) {
	s.RegisterService(&_Schema_serviceDesc, srv)
}

func _Schema_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Create(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Read(ctx, req.(*ReadSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Update(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Delete(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Schema_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Schema",
	HandlerType: (*SchemaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Schema_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Schema_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Schema_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Schema_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateClient interface {
	Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error)
	Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
}

type templateClient struct {
	cc *grpc.ClientConn
}

func NewTemplateClient(cc *grpc.ClientConn) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error) {
	out := new(ReadTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
type TemplateServer interface {
	Create(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	Read(context.Context, *ReadTemplateRequest) (*ReadTemplateResponse, error)
	Update(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error)
	Delete(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
}

func RegisterTemplateServer(s *grpc.Server, srv TemplateServer) {
	s.RegisterService(&_Template_serviceDesc, srv)
}

func _Template_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Create(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Read(ctx, req.(*ReadTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Update(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Delete(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Template_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Template_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Template_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Template_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Template_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// InputClient is the client API for Input service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InputClient interface {
	Read(ctx context.Context, in *ReadInputRequest, opts ...grpc.CallOption) (*ReadInputResponse, error)
}

type inputClient struct {
	cc *grpc.ClientConn
}

func NewInputClient(cc *grpc.ClientConn) InputClient {
	return &inputClient{cc}
}

func (c *inputClient) Read(ctx context.Context, in *ReadInputRequest, opts ...grpc.CallOption) (*ReadInputResponse, error) {
	out := new(ReadInputResponse)
	err := c.cc.Invoke(ctx, "/grpc.Input/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputServer is the server API for Input service.
type InputServer interface {
	Read(context.Context, *ReadInputRequest) (*ReadInputResponse, error)
}

func RegisterInputServer(s *grpc.Server, srv InputServer) {
	s.RegisterService(&_Input_serviceDesc, srv)
}

func _Input_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Input/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputServer).Read(ctx, req.(*ReadInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Input_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Input",
	HandlerType: (*InputServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Input_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_4fed8f99a8a63f42) }

var fileDescriptor_storage_4fed8f99a8a63f42 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0xc4, 0x4d, 0x26, 0x05, 0xda, 0x4d, 0x9a, 0xba, 0x0e, 0x3f, 0x95, 0x51, 0x45,
	0xc5, 0x21, 0x15, 0xe9, 0xa9, 0xe2, 0x80, 0x5a, 0x08, 0x6a, 0x0f, 0x48, 0xc8, 0x94, 0x23, 0x54,
	0xdb, 0x78, 0x6b, 0x2c, 0x25, 0xb6, 0x59, 0x6f, 0x84, 0xb8, 0x21, 0x4e, 0x9c, 0x78, 0x06, 0x1e,
	0x80, 0xe7, 0xe0, 0xb9, 0x50, 0x76, 0xbd, 0x8e, 0xe3, 0x6c, 0x6a, 0x68, 0xd2, 0x5b, 0xbc, 0x3b,
	0xf3, 0xcd, 0x7c, 0xdf, 0xce, 0xb7, 0x1b, 0xb8, 0x13, 0xb3, 0x90, 0x62, 0x8f, 0x74, 0x23, 0x1a,
	0xb2, 0x10, 0x55, 0x3c, 0x1a, 0x0d, 0xac, 0xf5, 0x41, 0x38, 0x1a, 0x85, 0x81, 0x58, 0xb3, 0x1e,
	0x79, 0x61, 0xe8, 0x0d, 0xc9, 0x01, 0xff, 0xba, 0x1c, 0x5f, 0x1d, 0x30, 0x7f, 0x44, 0x62, 0x86,
	0x47, 0x91, 0x08, 0xb0, 0x3d, 0x68, 0xbe, 0xa4, 0x04, 0x33, 0xf2, 0x6e, 0xf0, 0x89, 0x8c, 0xb0,
	0x43, 0x3e, 0x8f, 0x49, 0xcc, 0x90, 0x05, 0xb5, 0x21, 0x0e, 0xbc, 0x31, 0xf6, 0x88, 0x59, 0xde,
	0xd5, 0xf6, 0xeb, 0x4e, 0xfa, 0x8d, 0x5a, 0x50, 0x65, 0x3e, 0x1b, 0x12, 0xb3, 0xc2, 0x37, 0xc4,
	0x07, 0x7a, 0x08, 0xe0, 0x92, 0x2b, 0x3f, 0xf0, 0x99, 0x1f, 0x06, 0x66, 0x95, 0x6f, 0x65, 0x56,
	0xec, 0x6f, 0x1a, 0xb4, 0x66, 0x2b, 0xc5, 0x51, 0x18, 0xc4, 0x04, 0xdd, 0x05, 0xdd, 0x77, 0x4d,
	0x8d, 0x27, 0xe8, 0xbe, 0x8b, 0x8e, 0x00, 0x06, 0x3c, 0xce, 0xbd, 0xc0, 0xcc, 0x34, 0x76, 0xb5,
	0xfd, 0x46, 0xcf, 0xea, 0x0a, 0x1e, 0x5d, 0xc9, 0xa3, 0x7b, 0x2e, 0x79, 0x38, 0xf5, 0x24, 0xfa,
	0x98, 0xa1, 0x07, 0x50, 0x26, 0x94, 0x9a, 0xf7, 0x78, 0x4e, 0xa3, 0x3b, 0xd1, 0xa3, 0xdb, 0xa7,
	0x34, 0xa4, 0xce, 0x64, 0xdd, 0x7e, 0x0c, 0x9b, 0x0e, 0xc1, 0xee, 0x2c, 0xd3, 0x5c, 0x79, 0xfb,
	0x8f, 0x0e, 0x28, 0x1b, 0xb5, 0xa0, 0xcb, 0x95, 0x0b, 0xb4, 0x0c, 0xef, 0x23, 0x80, 0x71, 0xe4,
	0xca, 0xd4, 0xb5, 0xe2, 0xd4, 0x24, 0x5a, 0xa4, 0xba, 0x64, 0x48, 0x92, 0xd4, 0x5a, 0x71, 0x6a,
	0x12, 0x5d, 0xac, 0xf6, 0x17, 0x68, 0xbe, 0xe7, 0x65, 0xae, 0xd5, 0xfb, 0x16, 0x26, 0x2d, 0x82,
	0xd6, 0x6c, 0xe1, 0xe4, 0x08, 0x97, 0x50, 0xa9, 0x80, 0xea, 0x1e, 0x34, 0x5f, 0x71, 0x59, 0xae,
	0x1f, 0xad, 0x08, 0x5a, 0xb3, 0x61, 0xd3, 0xc6, 0x6e, 0xe9, 0x0c, 0xde, 0xc0, 0x96, 0xf0, 0xdc,
	0x39, 0x19, 0x45, 0x43, 0xcc, 0x88, 0x6c, 0x2d, 0x55, 0xb6, 0xbc, 0x58, 0xd9, 0xca, 0x9c, 0xb2,
	0xdf, 0x35, 0x68, 0xe7, 0xf1, 0xfe, 0xc9, 0xc5, 0xd5, 0x15, 0xba, 0x78, 0x0f, 0x9a, 0x13, 0x7f,
	0xe6, 0x19, 0xe5, 0xc5, 0xfe, 0xad, 0x43, 0x6b, 0x36, 0x6e, 0x41, 0xa7, 0x37, 0x92, 0x62, 0x19,
	0x7e, 0xb3, 0x73, 0x68, 0xdc, 0xdc, 0xad, 0x6b, 0x2b, 0x9c, 0x94, 0x0f, 0xb0, 0x25, 0x4c, 0x53,
	0xa0, 0xeb, 0x0d, 0x27, 0x87, 0x42, 0x3b, 0x0f, 0xaf, 0x74, 0x65, 0x75, 0x85, 0xae, 0x7c, 0x02,
	0x5b, 0xc2, 0x6e, 0x45, 0xa3, 0x42, 0xa1, 0x9d, 0x0f, 0x54, 0x3a, 0x73, 0x95, 0x7a, 0xff, 0xd0,
	0x00, 0xce, 0x82, 0x68, 0xcc, 0xfa, 0x01, 0xa3, 0x5f, 0xe7, 0x54, 0xee, 0x40, 0x3d, 0xe6, 0x97,
	0xc4, 0x85, 0xef, 0x9a, 0xba, 0xb8, 0x16, 0xc5, 0xc2, 0x99, 0x8b, 0x10, 0x54, 0x5c, 0xcc, 0x30,
	0x3f, 0x81, 0x75, 0x87, 0xff, 0xce, 0xcd, 0x63, 0xe5, 0x3f, 0xe6, 0xd1, 0xbe, 0x80, 0x06, 0xef,
	0xe4, 0xb5, 0x3f, 0x64, 0x84, 0x5e, 0x5f, 0xfa, 0x50, 0x51, 0xa6, 0x25, 0xc8, 0x4d, 0xb1, 0x71,
	0xe0, 0x91, 0x6c, 0x01, 0x0c, 0x1b, 0x13, 0x27, 0xf2, 0x22, 0xf2, 0x0c, 0x36, 0xa6, 0x84, 0x4f,
	0x4b, 0x9c, 0xf2, 0x33, 0xa8, 0x0f, 0xc2, 0xc0, 0x15, 0x13, 0xa4, 0x73, 0xe4, 0x4d, 0x81, 0x9c,
	0xe9, 0xee, 0xb4, 0xe4, 0x4c, 0xa3, 0x4e, 0x6a, 0x60, 0x5c, 0xf1, 0x65, 0xfb, 0xa3, 0x78, 0xda,
	0x93, 0x12, 0xc9, 0xe9, 0x3d, 0x85, 0x35, 0x12, 0x30, 0xea, 0x93, 0xd8, 0xd4, 0x76, 0xcb, 0xfb,
	0x8d, 0xde, 0x46, 0x06, 0x8f, 0xeb, 0xee, 0xc8, 0x80, 0x82, 0xe3, 0xea, 0xfd, 0xd4, 0xc1, 0x10,
	0xb7, 0x36, 0x3a, 0x06, 0x43, 0xdc, 0x81, 0x68, 0x47, 0x84, 0x29, 0xfe, 0x3f, 0x59, 0x96, 0x6a,
	0x4b, 0xb4, 0x65, 0x97, 0xd0, 0x73, 0xa8, 0x4c, 0xba, 0x45, 0xdb, 0x22, 0x6a, 0xee, 0x4f, 0x89,
	0x65, 0xce, 0x6f, 0xa4, 0xc9, 0xc7, 0x60, 0x08, 0x2b, 0xc9, 0xfa, 0x8a, 0x57, 0x56, 0xd6, 0x57,
	0xbd, 0x83, 0x02, 0x42, 0x0c, 0xbc, 0x84, 0x50, 0xbc, 0x5e, 0x12, 0x42, 0xf5, 0x62, 0xd9, 0xa5,
	0xde, 0x2f, 0x1d, 0x6a, 0xd2, 0x2e, 0xa8, 0x9f, 0x4a, 0xd2, 0xc9, 0xf2, 0xce, 0xf9, 0xce, 0xba,
	0xaf, 0xde, 0x4c, 0xdb, 0x7a, 0x91, 0xc8, 0xb2, 0x33, 0x65, 0x9f, 0x87, 0xb0, 0x54, 0x5b, 0x29,
	0x40, 0x3f, 0x95, 0xa6, 0x93, 0xe5, 0xbf, 0xa0, 0x0f, 0xf5, 0x85, 0x24, 0x60, 0x12, 0x79, 0x3a,
	0x59, 0x0d, 0x16, 0xc0, 0xa8, 0xaf, 0x0e, 0xbb, 0xd4, 0x3b, 0x81, 0x2a, 0x9f, 0x34, 0x74, 0x94,
	0xf0, 0x6a, 0x4f, 0x9b, 0xcf, 0x7a, 0xc1, 0xda, 0x9e, 0x5b, 0x97, 0x18, 0x6f, 0x4b, 0x97, 0x06,
	0x37, 0xef, 0xe1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0xb0, 0x39, 0xdf, 0xed, 0x0b, 0x00,
	0x00,
}
