// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kamilsk/form-api/server (interfaces: Service)

// Package server_test is a generated GoMock package.
package server_test

import (
	gomock "github.com/golang/mock/gomock"
	v1 "github.com/kamilsk/form-api/transfer/api/v1"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// HandleGetV1 mocks base method
func (m *MockService) HandleGetV1(arg0 v1.GetRequest) v1.GetResponse {
	ret := m.ctrl.Call(m, "HandleGetV1", arg0)
	ret0, _ := ret[0].(v1.GetResponse)
	return ret0
}

// HandleGetV1 indicates an expected call of HandleGetV1
func (mr *MockServiceMockRecorder) HandleGetV1(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetV1", reflect.TypeOf((*MockService)(nil).HandleGetV1), arg0)
}

// HandlePostV1 mocks base method
func (m *MockService) HandlePostV1(arg0 v1.PostRequest) v1.PostResponse {
	ret := m.ctrl.Call(m, "HandlePostV1", arg0)
	ret0, _ := ret[0].(v1.PostResponse)
	return ret0
}

// HandlePostV1 indicates an expected call of HandlePostV1
func (mr *MockServiceMockRecorder) HandlePostV1(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePostV1", reflect.TypeOf((*MockService)(nil).HandlePostV1), arg0)
}
