// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaRequest) Reset()         { *m = CreateSchemaRequest{} }
func (m *CreateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaRequest) ProtoMessage()    {}
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{0}
}
func (m *CreateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaRequest.Unmarshal(m, b)
}
func (m *CreateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaRequest.Merge(dst, src)
}
func (m *CreateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaRequest.Size(m)
}
func (m *CreateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaRequest proto.InternalMessageInfo

type CreateSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaResponse) Reset()         { *m = CreateSchemaResponse{} }
func (m *CreateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaResponse) ProtoMessage()    {}
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{1}
}
func (m *CreateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaResponse.Unmarshal(m, b)
}
func (m *CreateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaResponse.Merge(dst, src)
}
func (m *CreateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaResponse.Size(m)
}
func (m *CreateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaResponse proto.InternalMessageInfo

type ReadSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSchemaRequest) Reset()         { *m = ReadSchemaRequest{} }
func (m *ReadSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaRequest) ProtoMessage()    {}
func (*ReadSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{2}
}
func (m *ReadSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaRequest.Unmarshal(m, b)
}
func (m *ReadSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaRequest.Merge(dst, src)
}
func (m *ReadSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaRequest.Size(m)
}
func (m *ReadSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaRequest proto.InternalMessageInfo

type ReadSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSchemaResponse) Reset()         { *m = ReadSchemaResponse{} }
func (m *ReadSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSchemaResponse) ProtoMessage()    {}
func (*ReadSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{3}
}
func (m *ReadSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSchemaResponse.Unmarshal(m, b)
}
func (m *ReadSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *ReadSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSchemaResponse.Merge(dst, src)
}
func (m *ReadSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSchemaResponse.Size(m)
}
func (m *ReadSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSchemaResponse proto.InternalMessageInfo

type UpdateSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaRequest) Reset()         { *m = UpdateSchemaRequest{} }
func (m *UpdateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaRequest) ProtoMessage()    {}
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{4}
}
func (m *UpdateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaRequest.Unmarshal(m, b)
}
func (m *UpdateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaRequest.Merge(dst, src)
}
func (m *UpdateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaRequest.Size(m)
}
func (m *UpdateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaRequest proto.InternalMessageInfo

type UpdateSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaResponse) Reset()         { *m = UpdateSchemaResponse{} }
func (m *UpdateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaResponse) ProtoMessage()    {}
func (*UpdateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{5}
}
func (m *UpdateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaResponse.Unmarshal(m, b)
}
func (m *UpdateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaResponse.Merge(dst, src)
}
func (m *UpdateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaResponse.Size(m)
}
func (m *UpdateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaResponse proto.InternalMessageInfo

type DeleteSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaRequest) Reset()         { *m = DeleteSchemaRequest{} }
func (m *DeleteSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaRequest) ProtoMessage()    {}
func (*DeleteSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{6}
}
func (m *DeleteSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaRequest.Unmarshal(m, b)
}
func (m *DeleteSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaRequest.Merge(dst, src)
}
func (m *DeleteSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaRequest.Size(m)
}
func (m *DeleteSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaRequest proto.InternalMessageInfo

type DeleteSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaResponse) Reset()         { *m = DeleteSchemaResponse{} }
func (m *DeleteSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaResponse) ProtoMessage()    {}
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_91b3b9db1fccdd39, []int{7}
}
func (m *DeleteSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaResponse.Unmarshal(m, b)
}
func (m *DeleteSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaResponse.Merge(dst, src)
}
func (m *DeleteSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaResponse.Size(m)
}
func (m *DeleteSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateSchemaRequest)(nil), "grpc.CreateSchemaRequest")
	proto.RegisterType((*CreateSchemaResponse)(nil), "grpc.CreateSchemaResponse")
	proto.RegisterType((*ReadSchemaRequest)(nil), "grpc.ReadSchemaRequest")
	proto.RegisterType((*ReadSchemaResponse)(nil), "grpc.ReadSchemaResponse")
	proto.RegisterType((*UpdateSchemaRequest)(nil), "grpc.UpdateSchemaRequest")
	proto.RegisterType((*UpdateSchemaResponse)(nil), "grpc.UpdateSchemaResponse")
	proto.RegisterType((*DeleteSchemaRequest)(nil), "grpc.DeleteSchemaRequest")
	proto.RegisterType((*DeleteSchemaResponse)(nil), "grpc.DeleteSchemaResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchemaClient is the client API for Schema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchemaClient interface {
	Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error)
	Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error)
	Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error)
	Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
}

type schemaClient struct {
	cc *grpc.ClientConn
}

func NewSchemaClient(cc *grpc.ClientConn) SchemaClient {
	return &schemaClient{cc}
}

func (c *schemaClient) Create(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error) {
	out := new(CreateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Read(ctx context.Context, in *ReadSchemaRequest, opts ...grpc.CallOption) (*ReadSchemaResponse, error) {
	out := new(ReadSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Update(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error) {
	out := new(UpdateSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaClient) Delete(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, "/grpc.Schema/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServer is the server API for Schema service.
type SchemaServer interface {
	Create(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error)
	Read(context.Context, *ReadSchemaRequest) (*ReadSchemaResponse, error)
	Update(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error)
	Delete(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
}

func RegisterSchemaServer(s *grpc.Server, srv SchemaServer) {
	s.RegisterService(&_Schema_serviceDesc, srv)
}

func _Schema_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Create(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Read(ctx, req.(*ReadSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Update(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schema_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Schema/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServer).Delete(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Schema_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Schema",
	HandlerType: (*SchemaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Schema_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Schema_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Schema_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Schema_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_schema_91b3b9db1fccdd39) }

var fileDescriptor_schema_91b3b9db1fccdd39 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xce, 0x48,
	0xcd, 0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x12,
	0xe5, 0x12, 0x76, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x06, 0xcb, 0x05, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x28, 0x89, 0x71, 0x89, 0xa0, 0x0a, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x09,
	0x73, 0x09, 0x06, 0xa5, 0x26, 0xa6, 0xa0, 0x2a, 0x16, 0xe1, 0x12, 0x42, 0x16, 0x84, 0x2a, 0x15,
	0xe5, 0x12, 0x0e, 0x2d, 0x48, 0xc1, 0x66, 0x32, 0xaa, 0x30, 0x42, 0xb9, 0x4b, 0x6a, 0x4e, 0x2a,
	0x16, 0xe5, 0xa8, 0xc2, 0x10, 0xe5, 0x46, 0x7d, 0x4c, 0x5c, 0x6c, 0x10, 0x21, 0x21, 0x47, 0x2e,
	0x36, 0x88, 0x5b, 0x85, 0x24, 0xf5, 0x40, 0x7e, 0xd2, 0xc3, 0xe2, 0x21, 0x29, 0x29, 0x6c, 0x52,
	0x50, 0xab, 0x19, 0x84, 0xac, 0xb9, 0x58, 0x40, 0x3e, 0x10, 0x12, 0x87, 0xa8, 0xc2, 0xf0, 0xa2,
	0x94, 0x04, 0xa6, 0x04, 0x5c, 0xb3, 0x23, 0x17, 0x1b, 0xc4, 0x47, 0x30, 0xfb, 0xb1, 0x78, 0x1b,
	0x66, 0x3f, 0x56, 0xaf, 0x83, 0x8d, 0x80, 0xf8, 0x12, 0x66, 0x04, 0x96, 0xa0, 0x80, 0x19, 0x81,
	0x2d, 0x38, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xb1, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4a,
	0x73, 0x85, 0x4f, 0xe5, 0x01, 0x00, 0x00,
}
