// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTemplateRequest) Reset()         { *m = CreateTemplateRequest{} }
func (m *CreateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateRequest) ProtoMessage()    {}
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{0}
}
func (m *CreateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateRequest.Unmarshal(m, b)
}
func (m *CreateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateRequest.Merge(dst, src)
}
func (m *CreateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateRequest.Size(m)
}
func (m *CreateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateRequest proto.InternalMessageInfo

type CreateTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTemplateResponse) Reset()         { *m = CreateTemplateResponse{} }
func (m *CreateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTemplateResponse) ProtoMessage()    {}
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{1}
}
func (m *CreateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTemplateResponse.Unmarshal(m, b)
}
func (m *CreateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTemplateResponse.Merge(dst, src)
}
func (m *CreateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTemplateResponse.Size(m)
}
func (m *CreateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTemplateResponse proto.InternalMessageInfo

type ReadTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTemplateRequest) Reset()         { *m = ReadTemplateRequest{} }
func (m *ReadTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateRequest) ProtoMessage()    {}
func (*ReadTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{2}
}
func (m *ReadTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateRequest.Unmarshal(m, b)
}
func (m *ReadTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateRequest.Merge(dst, src)
}
func (m *ReadTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateRequest.Size(m)
}
func (m *ReadTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateRequest proto.InternalMessageInfo

type ReadTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTemplateResponse) Reset()         { *m = ReadTemplateResponse{} }
func (m *ReadTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTemplateResponse) ProtoMessage()    {}
func (*ReadTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{3}
}
func (m *ReadTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTemplateResponse.Unmarshal(m, b)
}
func (m *ReadTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *ReadTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTemplateResponse.Merge(dst, src)
}
func (m *ReadTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTemplateResponse.Size(m)
}
func (m *ReadTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTemplateResponse proto.InternalMessageInfo

type UpdateTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTemplateRequest) Reset()         { *m = UpdateTemplateRequest{} }
func (m *UpdateTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateRequest) ProtoMessage()    {}
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{4}
}
func (m *UpdateTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateRequest.Unmarshal(m, b)
}
func (m *UpdateTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateRequest.Merge(dst, src)
}
func (m *UpdateTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateRequest.Size(m)
}
func (m *UpdateTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateRequest proto.InternalMessageInfo

type UpdateTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{5}
}
func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(dst, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

type DeleteTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTemplateRequest) Reset()         { *m = DeleteTemplateRequest{} }
func (m *DeleteTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateRequest) ProtoMessage()    {}
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{6}
}
func (m *DeleteTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateRequest.Unmarshal(m, b)
}
func (m *DeleteTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateRequest.Merge(dst, src)
}
func (m *DeleteTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateRequest.Size(m)
}
func (m *DeleteTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateRequest proto.InternalMessageInfo

type DeleteTemplateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTemplateResponse) Reset()         { *m = DeleteTemplateResponse{} }
func (m *DeleteTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTemplateResponse) ProtoMessage()    {}
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_b5679afad9102e4e, []int{7}
}
func (m *DeleteTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTemplateResponse.Unmarshal(m, b)
}
func (m *DeleteTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTemplateResponse.Merge(dst, src)
}
func (m *DeleteTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTemplateResponse.Size(m)
}
func (m *DeleteTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTemplateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateTemplateRequest)(nil), "grpc.CreateTemplateRequest")
	proto.RegisterType((*CreateTemplateResponse)(nil), "grpc.CreateTemplateResponse")
	proto.RegisterType((*ReadTemplateRequest)(nil), "grpc.ReadTemplateRequest")
	proto.RegisterType((*ReadTemplateResponse)(nil), "grpc.ReadTemplateResponse")
	proto.RegisterType((*UpdateTemplateRequest)(nil), "grpc.UpdateTemplateRequest")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "grpc.UpdateTemplateResponse")
	proto.RegisterType((*DeleteTemplateRequest)(nil), "grpc.DeleteTemplateRequest")
	proto.RegisterType((*DeleteTemplateResponse)(nil), "grpc.DeleteTemplateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateClient interface {
	Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error)
	Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
}

type templateClient struct {
	cc *grpc.ClientConn
}

func NewTemplateClient(cc *grpc.ClientConn) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) Create(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Read(ctx context.Context, in *ReadTemplateRequest, opts ...grpc.CallOption) (*ReadTemplateResponse, error) {
	out := new(ReadTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Update(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Delete(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Template/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
type TemplateServer interface {
	Create(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	Read(context.Context, *ReadTemplateRequest) (*ReadTemplateResponse, error)
	Update(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error)
	Delete(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
}

func RegisterTemplateServer(s *grpc.Server, srv TemplateServer) {
	s.RegisterService(&_Template_serviceDesc, srv)
}

func _Template_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Create(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Read(ctx, req.(*ReadTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Update(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Template/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Delete(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Template_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Template_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Template_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Template_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Template_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_template_b5679afad9102e4e) }

var fileDescriptor_template_b5679afad9102e4e = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0xcd, 0x2d,
	0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48,
	0x56, 0x12, 0xe7, 0x12, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x81, 0xca, 0x06, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x28, 0x49, 0x70, 0x89, 0xa1, 0x4b, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7,
	0x2a, 0x89, 0x72, 0x09, 0x07, 0xa5, 0x26, 0xa6, 0xa0, 0x6b, 0x10, 0xe3, 0x12, 0x41, 0x15, 0x86,
	0x2a, 0x17, 0xe7, 0x12, 0x0d, 0x2d, 0x48, 0xc1, 0x6e, 0x03, 0xba, 0x04, 0x42, 0x8b, 0x4b, 0x6a,
	0x4e, 0x2a, 0x56, 0x2d, 0xe8, 0x12, 0x10, 0x2d, 0x46, 0x0b, 0x98, 0xb8, 0x38, 0x60, 0x82, 0x42,
	0xae, 0x5c, 0x6c, 0x10, 0xb7, 0x0b, 0x49, 0xeb, 0x81, 0x7c, 0xa9, 0x87, 0xd5, 0x8b, 0x52, 0x32,
	0xd8, 0x25, 0xa1, 0x8e, 0x60, 0x10, 0xb2, 0xe7, 0x62, 0x01, 0xf9, 0x48, 0x48, 0x12, 0xa2, 0x0e,
	0x8b, 0xa7, 0xa5, 0xa4, 0xb0, 0x49, 0xc1, 0x0d, 0x70, 0xe5, 0x62, 0x83, 0xf8, 0x10, 0xe6, 0x0e,
	0xac, 0x01, 0x01, 0x73, 0x07, 0x8e, 0xc0, 0x00, 0x1b, 0x03, 0xf1, 0x35, 0xcc, 0x18, 0xac, 0x81,
	0x03, 0x33, 0x06, 0x7b, 0x00, 0x29, 0x31, 0x24, 0xb1, 0x81, 0xe3, 0xdd, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x65, 0x6c, 0x85, 0x12, 0x09, 0x02, 0x00, 0x00,
}
