### API v1

POST http://admin:admin@localhost:8080/api/v1
Content-Type: application/xml

<form title="Email subscription" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

GET http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Accept: application/xml

###

PUT http://admin:admin@localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/xml

<form title="Email subscription" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

DELETE http://admin:admin@localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4

###

POST http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/x-www-form-urlencoded

email=test@my.email

### API v2

POST http://admin:admin@localhost:8080/api/v2/schema
Content-Type: application/xml

<form title="Email subscription" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

GET http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Accept: application/xml

###

PUT http://admin:admin@localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/xml

<form title="Email subscription" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

DELETE http://admin:admin@localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4

###

POST http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/x-www-form-urlencoded

email=test@my.email

###

POST http://admin:admin@localhost:8080/api/v2/template
Content-Type: text/html

<form id="form-{{ .ID }}" title="{{ .Title }}"
      action="{{ .Action }}" method="{{ .Method }}" enctype="{{ .EncodingType }}">
    <div class="form-group">
        {{ range where .Inputs "Name" "email" }}
        <label for="input-{{ .ID }}">{{ .Title }}</label>
        <input id="input-{{ .ID }}" name="{{ .Name }}" type="{{ .Type }}" title="{{ .Title }}" {{ extra . }}>
        {{ end }}
    </div>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

GET http://localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1
Accept: text/html

###

PUT http://admin:admin@localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1
Content-Type: text/html

<form id="form-{{ .ID }}" title="{{ .Title }}"
      action="{{ .Action }}" method="{{ .Method }}" enctype="{{ .EncodingType }}">
    <div class="form-group">
        {{ range where .Inputs "Name" "email" }}
        <label for="input-{{ .ID }}">{{ .Title }}</label>
        <input id="input-{{ .ID }}" name="{{ .Name }}" type="{{ .Type }}" title="{{ .Title }}" {{ extra . }}>
        {{ end }}
    </div>
    <input name="_redirect" type="hidden" value="https://kamil.samigullin.info/"/>
</form>

###

DELETE http://admin:admin@localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1

###

GET http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4/template/4405940a-03c2-4840-b66d-937c59f109c1
Accept: text/html

### Profiling

GET http://admin:admin@localhost:8080/debug/pprof/cmdline

###

GET http://admin:admin@localhost:8080/debug/pprof/profile

###

GET http://admin:admin@localhost:8080/debug/pprof/symbol

###

GET http://admin:admin@localhost:8080/debug/pprof/trace

###

GET http://admin:admin@localhost:8080/debug/pprof

###

GET http://admin:admin@localhost:8080/debug/pprof/goroutine

###

GET http://admin:admin@localhost:8080/debug/pprof/threadcreate

###

GET http://admin:admin@localhost:8080/debug/pprof/heap

###

GET http://admin:admin@localhost:8080/debug/pprof/block

###

GET http://admin:admin@localhost:8080/debug/pprof/mutex
