### API v1

POST http://localhost:8080/api/v1
Content-Type: application/xml

<form lang="en" title="Email subscription"
      action="https://kamil.samigullin.info/" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
</form>

###

GET http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Accept: application/xml

###

PUT http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/xml

<form lang="en" title="Email subscription"
      action="https://kamil.samigullin.info/" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
</form>

###

DELETE http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4

###

POST http://localhost:8080/api/v1/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/x-www-form-urlencoded

email=test@my.email

### API v2

POST http://localhost:8080/api/v2/schema
Content-Type: application/xml

<form lang="en" title="Email subscription"
      action="https://kamil.samigullin.info/" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
</form>

###

GET http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Accept: application/xml

###

PUT http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/xml

<form lang="en" title="Email subscription"
      action="https://kamil.samigullin.info/" method="post" enctype="application/x-www-form-urlencoded">
    <input name="email" type="email" title="Email" maxlength="64" required="1"/>
</form>

###

DELETE http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4

###

POST http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4
Content-Type: application/x-www-form-urlencoded

email=test@my.email

###

POST http://localhost:8080/api/v2/template
Content-Type: text/html

<form id="form-{{ .ID }}" lang="{{ .Language }}" title="{{ .Title }}"
      action="{{ .Action }}" method="{{ .Method }}" enctype="{{ .EncodingType }}">
    <div class="form-group">
        {{ range where .Inputs "Name" "email" }}
        <label for="input-{{ .ID }}">{{ .Title }}</label>
        <input id="input-{{ .ID }}" name="{{ .Name }}" type="{{ .Type }}" title="{{ .Title }}" {{ extra . }}>
        {{ end }}
    </div>
    <input type="submit">
</form>

###

GET http://localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1
Accept: text/html

###

PUT http://localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1
Content-Type: text/html

<form id="form-{{ .ID }}" lang="{{ .Language }}" title="{{ .Title }}"
      action="{{ .Action }}" method="{{ .Method }}" enctype="{{ .EncodingType }}">
    <div class="form-group">
        {{ range where .Inputs "Name" "email" }}
        <label for="input-{{ .ID }}">{{ .Title }}</label>
        <input id="input-{{ .ID }}" name="{{ .Name }}" type="{{ .Type }}" title="{{ .Title }}" {{ extra . }}>
        {{ end }}
    </div>
    <input type="submit">
</form>

###

DELETE http://localhost:8080/api/v2/template/4405940a-03c2-4840-b66d-937c59f109c1

###

GET http://localhost:8080/api/v2/schema/41ca5e09-3ce2-4094-b108-3ecc257c6fa4/template/4405940a-03c2-4840-b66d-937c59f109c1
Accept: text/html

### Profiling

GET http://localhost:8090/pprof/cmdline

###

GET http://localhost:8090/pprof/profile

###

GET http://localhost:8090/pprof/symbol

###

GET http://localhost:8090/pprof/trace

###

GET http://localhost:8090/debug/pprof/

### Monitoring

GET http://localhost:8091/vars

###
